### ISSUE TITLE
Update the open-data conversion for CUK with the correct mapping for CUK vocabs

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/open-data#139]
> I think the ESSGlobal Org Structure isn't getting mapped correctly - Has that been wired yet?

We identified that the problem here stemmed from an error in the ods file used in the construction of the csv files used to map Co-ops UK's Legal Form and Ownership Classification onto ESS Global's Org Structure and Base Membership Type. This has been fixed. Once the data has been reprocessed and deployed with the corrected vocab mapping (and with latest co-ops uk data) we can test again.

_Originally posted by @ColmMassey in https://github.com/DigitalCommons/technology-and-infrastructure/issues/80#issuecomment-1299093111_

**Comment by ColmDC** [comment]
Data seems to be much healthier now, so I think that that issue has been resolved. Addressing this did highlight the fragility of this process, so have created this ticket to address this. https://github.com/DigitalCommons/map-sse/issues/5 Add any more refelctions, suggestions to that ticket.
