### ISSUE TITLE
[OBO MykoMap] Fix ObO airtable sync now that Airtable API has changed

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/open-data#185]
Please track against the clockify project [[OBO MykoMap](https://app.clockify.me/projects/65e885153676853154ffc5ab/edit)]

## Description
The data feed download from the OBO Airtable API seems to have stopped working.

It could be related to this email Airtable sent at the end of last year, although this is not slated to come into effect until Feb 1st 2024:
> You’re receiving this update because you have used the Airtable API via an API key in the last six months. 
> 
> At the start of this year, we [launched new API authentication methods](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=b3cc4102ebfd4b6ea3982def80cfea90&_e=8RQPWHXvqQjhbSswcaBvM1-ighO5AGZ-dPhxMMpM7YRiNUqpGh6iiNCWTVpwpomjVTONCUkxfM0Lt3dOKmHyhogHTf7a281nE5Z_biAcmphRGPBSn8uvUbmr-Z7S9gbgxXcXwM7kB9PEEOpEIh1Pxdht1GeLqfnuzgzUTtPDc-OqZ-0GmJCIfaOLmWh4ipNRGdVFKo7PE0xe3ntHsS3XIBJfV_1NC68heu3ZKXQVGHpYwZditPwuzqQY-B-GeYxwtAkZKaO8SlFKNiFCf91daGws-vNy8lWhn7rMYb1tZDmehxxvgbtdBmwA5_RUYHMahsPPJDFkP4aNvgOkSSZ93CSsSCMjlPsOJvS7_IXwq3zbgpy9xu0E1GMe9Xc75OEb7n_Xt2E1h-fFSHlzd2x8cibQnUDRQzueKrWl5yOeOFMldjUTKMNqqJBrwxpXaDYcFz6ekQ7N02G37n9kOwpjC53gyfDKWMdmEWvE1yo58pqwhjokeN2MlK9CdNljEZ0AFQjCMNYAKt0GUhrzSCW_TwnNS9JQMTZTYjWVd0gK5fJoPl1L8v-XgMYvD-uGMzN2ozKEnz8EAntdLFUq-_VtYA%3D%3D) and announced the upcoming deprecation of API keys on February 1st, 2024: this email is a reminder about this change. 
> 
> How does this impact you? API keys (and therefore, any integration that used them to connect with Airtable) will continue to work until February 1st 2024. However, to ensure continued access to the Airtable API, you will need to start using the new authentication methods before February 1st 2024.
> 
> If you have already stopped using your Airtable API key, no further action is required. For example, if you have previously provided your API key to Zapier, you will have previously received emails confirming that your Zaps have been automatically migrated, and no further action is required for your Zapier usage (but may be required if you also provided your API key to other integrations or services)
> 
> If you or a developer on your team has used an Airtable API key to build API integrations with Airtable, please migrate to using [personal access tokens](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=b3cc4102ebfd4b6ea3982def80cfea90&_e=8RQPWHXvqQjhbSswcaBvMzOBClND_g8vGzypqd3RFwjB4-5PS9gxveOy6c6VEmuXiB0gAmczpuBDo10-oWJFZtWeA8b6bPzDkWwPOzH0Wt9dTLwMVHpH1OaHMyTulHcpKpgixalvfxe3CRiqW40isLXX2tMigmbgUGG-rRoshcfsJ5mm35rj_g6-7qXiYdCYZadnIKNXfyyhksVg4uXfzryC3psEXOSj1NDjtd-nJ4Lk6RARX3EpwJOENut5vw7i8STG_dvhEJXiRdT-eAz9mATYuI8Rvj9bPKufy-YLybMk4xpuwTftmyNI-rEqvyl5ewDmgHwsIsRUWqO9fHOAvFfZH2nTxZJakTziN87fGrSvvtpKP8P4TukjEfKgmmXZirTbyLxuJrIKk7QUc94x5aEUtAwYeVcTnCXOQ7WxkCXgs5FwtMxCinuSZGqO3MGBZBrZDTg42rkxB2HyHCRgCs2nY1ndjcXIaggQEfTS5TMezzJ1DvEnKFOZKvq_ztmp) to authenticate your API requests before February 1st 2024. Your API key usage can be directly replaced with a personal access token provided as an Authorization: Bearer header.
> 
> If your API Key use is with a third-party integration, we recommend using [OAuth for authentication](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=b3cc4102ebfd4b6ea3982def80cfea90&_e=8RQPWHXvqQjhbSswcaBvM3BJKikb4FcnDuqvH2fhmQhj_b6x3KrKeKg_akcLT8Rox-qypR--CwwHBTzrXJD8ki4Ecb3ghSFwJn--bU5egymUhXHWVnpllP_0vVvorJ6wLoo-pITu--2Z-ef5r_d98gEyPKaRtZ79hF188EHqqLCJ-QUzgbyJJiJt2yo5z1OTSYlAZhYFEqEPBkI4fcdG0lp86uuBpVKceN-4r-K0xdG5_iXti4b4ucnXv7RV22WF5V-tM8Tr26bi6bsiTHio_PiOn9iqIQPRFiyD31us2S8qiuEucJKFGWgqL9_9kLHfiMxSWiNQuvaXzELACNNt3hmqhcBYvnGGU7LS4yaNe5bLCbqRtYXZ5mjCVyja9pTIVq7aoKxHC8ZPQSnGWA3H__EBuRcYVeaRxVU9qcE0L7U7d5mORajZ3C3E0eAgAlDFGciIodsaNsM_pK5iBfNTp89fF7iJ5aG-AYRsvkewrrn77uyAiAiQQG7fi2GfuM5G-Alxt4ur4lnoJebWAgPasA%3D%3D). Many partners have already updated their integrations to support OAuth. If you are unsure how to set up OAuth for a specific partner or OAuth is not currently available for that partner, we recommend you contact their team for details on when it will be available. 
> 
> To learn more about this change, please visit our [support article](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=b3cc4102ebfd4b6ea3982def80cfea90&_e=8RQPWHXvqQjhbSswcaBvM3BJKikb4FcnDuqvH2fhmQgBMOni_DEA9UlZaReDStJLmiIFNA9Q9FDAiBV8rS3kV1N7wmOXrXiY4AjNd6nUmvXK5Wdg58qwgNQLmrrzGNP0V4RewUUBikW0QHvx6chU8qhLZHNUHJD3IZyMujM63H-T10oHOBDQHTkqdbFTi9OKMTPk6K7jg3Pf-ss4SML43qV2O6nm_kUqTn0tbZC3H40BlqSYFJU_1GW4zDNYbi8SOIJY4Aal-GJF1XaXuuwGfMQ8R8LzHlMp_eziBqccW0PsG3CYAIJk050In__eRFgrq7As_4pKi-592KzMhsV8wOCs7OngOViTT5FQ1Lo7-wPxvGamOYNOvXMpPipwaTbxNIIK79tQ83MzyohH0cuYW5uI52fPEtwirzdJ8Nx30JpW1I4Dgw-OIZswW8kGqSKWO6X5nR7UbwN_oCj8mSq1X04qEjSSMAj0UGYWLR_3-tKmp7T3dxvcX5H7zYoMr41R), which contains recommendations about how to find what is using your API key, and how to migrate to personal access tokens and OAuth.

More details https://support.airtable.com/docs/airtable-api-key-deprecation-notice

In any case, this needs more investigation.

## Acceptance Criteria

- The data is being downloaded when requested.
- The data is being processed for the map as before.
- Changes made to data within Airtable are appearing on the https://maps.solidarityeconomy.coop/obo-public/ map within 15 minutes.

**Comment by wu-lee** [comment]
The error is only evident when the download is actually triggered (not suppressed because it thinks the data is up to date). To force a download, I've moved the data aside and run the downloader. It gets a 403 unauthorised error.

```
$ bundle exec seod download
invoking command: download
Traceback (most recent call last):
        4: from /home/seopendata/working/owned-by-oxford/downloader:13:in `<main>'
        3: from /home/seopendata/working/owned-by-oxford/.gems/ruby/2.7.0/bundler/gems/se-open-data-d26ba8a077c1/lib/se_open_data/cli.rb:232:in `command_http_download'
        2: from /home/seopendata/working/owned-by-oxford/.gems/ruby/2.7.0/bundler/gems/se-open-data-d26ba8a077c1/lib/se_open_data/cli.rb:671:in `fetch'
        1: from /usr/lib/ruby/2.7.0/net/http/response.rb:133:in `value'
/usr/lib/ruby/2.7.0/net/http/response.rb:124:in `error!': 403 "Forbidden" (Net::HTTPServerException)
'downloader' command in current directory failed
/home/seopendata/working/owned-by-oxford/.gems/ruby/2.7.0/bundler/gems/se-open-data-d26ba8a077c1/lib/se_open_data/cli.rb:282:in `command_download'
/home/seopendata/working/owned-by-oxford/.gems/ruby/2.7.0/bundler/gems/se-open-data-d26ba8a077c1/bin/seod:128:in `<top (required)>'
/home/seopendata/working/owned-by-oxford/.gems/ruby/2.7.0/bin/seod:23:in `load'
/home/seopendata/working/owned-by-oxford/.gems/ruby/2.7.0/bin/seod:23:in `<main>'
```

**Comment by lin-d-hop** [comment]
Feels to me like this would benefit from an initial timeboxed investigation to understand:

1. Is there a simple fix? If so just fix it.
2. If not, are there different potential solutions to chat through.
3. Does the auth update require a separate issue?

**Comment by ColmDC** [comment]
Spend a couple of hours to see if there is a straight forward fix.

**Comment by ColmDC** [comment]
Definitley seem to be some changes on 

https://maps.solidarityeconomy.coop/obo-public/

Can you have a quick check that the obvious new geo-coding issues are not related to these fixes you've made, and I'll raise a seperate ticket to look into them. @wu-lee

**Comment by ColmDC** [comment]
Okay, clearly not related to Airtable issue, we should close this, but I think we should start a wiki page noting known weaknesses with our geocoder, and recommendations on how to feed it to get the best results.
