### ISSUE TITLE
Lime Survey/data capture additional jobs

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/open-data#36]
This is to capture the jobs mentioned [here][1] in #2 

[1]: https://github.com/SolidarityEconomyAssociation/open-data/issues/2#issuecomment-652077347

To try and itemise the suggestions somewhat:

- A more concise (one-line or empty) cron notification, with more verbose diagnostics written to a (rotated) log
- Think about limiting the attack surface of the deployment steps, which have to run as root currently.
- Eliminate duplicated verification functions, present in more than one `converter` script, etc.
- Think about the data input and output formats, e.g. encodings, mark-up or tags allowed. Users already try to add line-feeds, paragraphs, bullet points, etc.
- Thereby validate data to protect against bad/sloppy input.
- Likewise prevent script injection, or just loss of formatting (line-feeds and angle brackets being eaten in HTML; mojibake due to unicode mis-conversion; linkification of URLs, etc.)
- Documentation.
- Deal with schema changes so that Lime Survey and the conversion keep in step.
- Allow other config such as notification emails to be detected and used 
- Support other sources than Lime Survey?

These may need to be split into sub-issues.

**Comment by wu-lee** [comment]
Also:
- Consider using a dedicated gpg key for deployment instead of exported passwords loaded into the environment from a file
- Add a dedicated limesurvey account for limesurvey exports (instead of using mine: `Nick`)

**Comment by ColmMassey** [comment]
How do we deal with changes to vocabularies rippling back to the surveys?
At least we need add Limesurvey documentation to update survey terms from latest vocab.

**Comment by wu-lee** [comment]
I've asked how to tell when there is new survey response data here:

https://forums.limesurvey.org/forum/can-i-do-this-with-limesurvey/122433-how-to-check-if-a-survey-s-has-new-or-modified-responses-programmatically
