### ISSUE TITLE
Create Mutual Aid Extension to ESSGlobal

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/open-data#52]
How should we describe the Mutual Aid Groups in our schemas?

Should we create a new  Organisational Structure VES or is it a Qualifier?

**Comment by ColmMassey** [comment]
We should stop classifying them by default as Co-operatives.

**Comment by wu-lee** [comment]
See also https://github.com/SolidarityEconomyAssociation/covid-mutual-aid-project/issues/1#issuecomment-810397018

**Comment by ColmMassey** [comment]
Save this extension for the next iteration. Let's roll out and bed in the current changes across existing maps and datasets first.
