### ISSUE TITLE
Migrate coops-uk dataset to Ruby driven conversion

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/open-data#62]
For consistency, everything really needs to be built uniformly on the servers with Ruby. 

_Originally posted by @ColmMassey in https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/235#issuecomment-733765206_

**Comment by ColmMassey** [comment]
Can this be closed? @wu-lee

**Comment by wu-lee** [comment]
Yes.
