### ISSUE TITLE
Please record here interesting applications that use Linked Data

### ISSUE THREAD

**Issue by matt-wallis** [DigitalCommons/open-data#8]
This issue arose from a need to be able to give people examples of Linked Data in action, especially examples which might be familiar to people who have probably not even heard of Linked Data.

A question  was put to the public-lod forum in the thread [Examples of applications built on LOD](https://lists.w3.org/Archives/Public/public-lod/2018Nov/0000.html).

**Comment by ColmMassey** [comment]
https://openengiadina.net/

Example of Integrating ActivityPub with Linked Data

**Comment by ColmMassey** [comment]
https://datafoodconsortium.gitbook.io/dfc-standard-documentation/

Open Food Network's linked data solution for mapping the local food production supply chain.

**Comment by ColmMassey** [comment]
https://startinblox.com/en/
French co-op Happdev's webcomponent framework for creating solid-linked data enabled applications.

**Comment by ColmMassey** [comment]
Some research papers using LOD for GIS work.

https://onlinelibrary.wiley.com/doi/epdf/10.1111/tgis.12538
https://www.youtube.com/watch?v=kluiPMaNHfM

**Comment by ColmMassey** [comment]
https://github.com/datafoodconsortium
