### ISSUE TITLE
dotcoop data glitch?

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/open-data#87]
Odd changes have been occuring in the dotcoop data source since Jonathan updated the URI we were using to download the data with on dev-1/prod-1.  This data seems to have triggered an error in the conversion which prevents it completing (which I'll add in a separate bug).

Specifically:
- The size of the new datafile seems 3x bigger than the one previously downloaded, and this previous one seems identical to the one we were getting prior to the URI update, whose latest registration date is in Aug 2020
- The new data file has many (all) rows triplicated (with slightly different last-modified dates)
- This includes a triplicated header row

My suspicion is the sequence of events is:
- non-working URL supplied
- new URL allows data to be downloaded
- data reverts at some point to the old (aug 2020) data?
- then correct data appears, but it breaks converter
- I refactor converter deduplication code. Maybe new data also has problems?

Jonathan has been notified, awaiting a reply...

**Comment by ColmDC** [comment]
Closing this as probably obsolete
