### ISSUE TITLE
nil value error halts dotcoop data deduplication

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/open-data#88]
Seems to have been triggered by #87, so it may just be that the somewhat weird new data coming at the moment breaks the de-duplication code.

[FIXME insert error here]

**Comment by wu-lee** [comment]
In order to understand the problem, I began some refactoring of the dotcoop merge-and-deduplicate code, aiming to make it intelligible (to me at least). Mostly following some general good practicises, splitting massive nested loops into subroutines.

I don't fully understand it, yet, but it does seem to result in no error when I re-process the new data file.

I'm comparing the result to the old datafile conversion output (i.e. a copy of the contents of `generated-data`) as a regression test, and that hasn't changed in the process, which gives some confidence it is still correct.

I think the deduplication code clearly can't see duplicates my eyeballs can. Typically same coop, slight spelling difference or address difference.
e.g.

    18224266,Banyan Project,"","","","",48-2 Kent Street,Newburyport,MA,01950,US,,http://matters.coop,"",...

vs

    18226825,Banyan Project,"","","","","",Newburyport,Massachusetts,01950,US,,http://banyanproject.coop,...

**Comment by ColmDC** [comment]
Obsolete?
